### ISSUE TITLE
プロジェクト名

### ISSUE THREAD

**Issue by terkel** [fontplus/web-typography-glossary#1]
Webタイポグラフィ用語集（仮）

**Comment by syyashiro** [comment]
日
Webタイポグラフィ必携用語集
英：
Web Typography Glossary

で一旦関口さん、土屋さんに確認お願いしておきます！

**Comment by terkel** [comment]
@syyashiro ていうか関口さん土屋さんナガクラさんもここに招待していただいた方が

**Comment by syyashiro** [comment]
「Webタイポグラフィ必携用語集」
というタイトルについてご相談です。

「必携」「用語集」が入ると
一冊の本のような、完成するものという印象を与えるのではと
タケルさんからご指摘をいただきました。
必携と用語集の組み合わせの印象かなと思いつつ、
下記のような別案を考えてみました。
練りすぎて、よく分からなくなってしまっている
感覚があるので、率直なご意見頂きたいです！
@tsuchir @sekig-ndc 

++++

**実践Webタイポグラフィ用語**
web-typography-glossary
（実践というコンセプトを伝えつつシンプルに）

**Webタイポグラフィ必携キーワード**
web-typography-keywords
（一番柔らかく、とっつきやすさを出す）

**Webタイポグラフィ用語要覧**
web-typography-glossary
（少し硬くしつつ、エッセンシャルなことを追加）

**Webタイポグラフィ用語解**
web-typography-glossary
（あくまで一つの解釈を述べていることを示す）

+++++

**Comment by tsuchir** [comment]
はじめての試みなので、なじみのあるスタンダードな言葉がよさそうなのは同意です！
あまりてらわずに、
Webタイポグラフィ用語解説・実践
とかでも。
別方向では『現代用語の基礎知識』みたいな名付けも面白いかも。イメージしやすいし。

**Comment by syyashiro** [comment]
いいとこ取りっぽいですが、

# Webタイポグラフィの基礎知識と実践

Webタイポグラフィに関するキーワードを解説、同分野における知見を蓄積・共有します。  

とすると内容もイメージしやすく、
内容にも即しているかなと思いました！

@tsuchir
