### ISSUE TITLE
READMEの編集

### ISSUE THREAD

**Issue by terkel** [fontplus/web-typography-glossary#108]
- 目次の見直し
- 五十音順の索引あると便利？
- タイトルロゴあるとうれしい

そのほか追加するとよいものあれば。

**Comment by terkel** [comment]
参考資料はけっこう参考になるのでもう少し大きくしてもいい気が。

**Comment by terkel** [comment]
いったん完結するので、「更新について」のセクションはトリでよさそうですね。

**Comment by tsuchir** [comment]
> 五十音順の索引あると便利？

50音順の索引は作成しましょう！

> 参考資料はけっこう参考になるのでもう少し大きくしてもいい気が。

こちらですが、大きくというのは記載の方法的に？目立たせたい意図としては同意です！

> 「更新について」のセクションはトリでよさそうですね。

議論自体はこれからもなされていってほしいですし、タイミングを設けて改訂・加筆していきたいので、ここの記載は残しつつ「第6回リリースで用語の追加は一旦終了しますが、議論とそれによる改訂・加筆等は継続しております。ぜひissueを立ててください」というようなコメントを付け加えるのはいかがでしょう？

**Comment by terkel** [comment]
@tsuchir 「参考資料」は記載として埋もれてしまっている印象があって、もう少しフィーチャーしてもいいかなと思った次第です。「更新について」は内容をアップデートして残すということで異論ないです！

**Comment by hrmtrui** [comment]
@terkel 土屋さん・関口さんよりご意見をいただき「更新について」の改定版を更新いたしました！
ご確認いただければ幸いです！

**Comment by terkel** [comment]
@hrmtrui @tsuchir @sekig-ndc 「更新について」の更新、ありがとうございます。ただいままでの経緯みたいな部分はもう少し端折ってもいいのではないかと感じました。たとえば以下のようなものだと簡単すぎますか？

```
2019年1月から不定期に更新を開始し、同年9月の[第6回リリース](https://github.com/fontplus/web-typography-glossary/pull/109)をもって用語の追加はいったん終了いたしました。今後も改訂・加筆等の提案は歓迎いたしますので、ぜひ気軽にissueを立ててください。
```

**Comment by hrmtrui** [comment]
@terkel ありがとうございます！@tsuchir @sekig-ndc　お二方と相談しまして、＜なぜ更新が一旦止まったかの経緯があったほうがよいのでは？＞とのことでしたので、タケルさんの修正版に、＜基本となる用語はカバーできたと考え用語の追加は一旦終了＞を付け加えるさせていただきたく。
--
2019年1月から不定期に更新を開始し、同年9月の[第6回リリース](https://github.com/fontplus/web-typography-glossary/pull/109)をもって基本となる用語はカバーできたと考え用語の追加は一旦終了しますが、今後も改訂・加筆等の提案は歓迎いたしますので、ぜひ気軽にissueを立ててください。
--
上記でいかがでしょうか？

**Comment by terkel** [comment]
@hrmtrui なるほど、たしかにそうですね。それでいきましょう！

あとちょっと細かいんですが、「……終了しますが、今後も……」と続くと一文が長すぎるので「……終了します。今後も……」と切ったほうが読みやすい気がするんですが、いかがでしょう？

**Comment by hrmtrui** [comment]
@terkel ありがとうございます！たしかに一文を切ったほうが読みやすいですね！では「終了します。今後も・・・」と修正入れておきます！
