### ISSUE TITLE
追加の図版

### ISSUE THREAD

**Issue by hrmtrui** [fontplus/web-typography-glossary#118]
追加の図版、及び現状の図版内容から変更を検討したものが以下になります。
ご確認お願いいたします！

「字体」
（TODO 図版：文字の骨格という抽象概念を表現するもの｜『さ』『令』様々な書体で）

「異字体」
（TODO 図版：「会」と「會」、「高」と「髙」）

「ローマン体」
（TODO 図版：ローマン体とセリフ体の図解）

「コンデンスト体」
（TODO 図版：コンデンスト書体の事例。同じファミリーでコンデンスト書体ではないものとの比較）

「エクスパンデッド体」
（TODO 図版：エクステンデッド体の事例。同じファミリーでエクステンデッド書体ではないものとの比較）

「スモールキャップ」
（TODO 図版：例文によってスモールキャップを明示する→本文組版で明示。）
例文：The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.

「セリフ体」「サンセリフ体」「スラブセリフ体」「明朝体」「ゴシック体」
（TODO 図版：「書体」で作成した図版の一部の引用）

「全角」
（TODO 図版：正方形の中に例文字「あ」）

「ボディ」
（TODO 図版：フォントの文字の部分とその周囲のスペースを含めた矩形）
→グリフからのつながりで「あ」の字を引用し、そのうえで「かな・漢字」も含め例を示す。
あわせて英数字のボディも示す。

「字面」
（TODO 図版：ボディで用いた図を持ってきて、背景色をしき、文字が描かれている部分をいつもの黒ではなく別の色で表して、その色＝字面）

「ベースライン」
（TODO 図版：アルファベットが整列する垂直方向の基準線で、「H」や「x」などの文字の下端が接する仮想のラインを明示する。）」

「文字サイズ」
（TODO 図版：和文と欧文、同じ文字サイズで大きさの印象が異なる書体を使用する）→和文と欧文でまとまった文章を作成し同じ級数で比較する
例文：海は昼眠る、夜も眠る、ごうごう、いびきをかいて眠る。
□「字間」「ベタ組み」「トラッキング」の図版の例文も「文字サイズ」と同様に

「ルビ」
（TODO 図版：縦組みの際のルビと、横組みの際のルビ、全ルビにする）
例文：国分寺駅の東口から路線バスに乗り5分ほど、いつもの中央公園で日の光がヒラヒラと反射する小川を臨む。

「圏点」
（TODO 図版：ルビの例文を流用、縦組み、横組み）（TODO 図版：白抜きゴマ）

「行頭揃え」「行末揃え」「中央揃え」「両端揃え」は
「行揃え」から引用する

「ハイフネーション」
（TODO 図版：英文の長文例を明示する。ハイフネーション有・無による読みやすさの比較）

「縦中横」
（TODO 図版：縦中横になっているテキスト。
例文：人類史上初の月面着陸は、アメリカ合衆国のアポロ11号（1969年）である。地球から月までの距離は、約37万㎞。）

「文字コード」
（TODO 図版：文字コードとグリフが合わさって文字が表現されている様子、概念図。文字コードのデータベースっぽいところから使う文字コードをいくつか出し、それがグリフのデータベースに照合されて文字が出力される）

**Comment by terkel** [comment]
残り：

- [ ] 文字サイズ
- [ ] ルビ
- [ ] 圏点
- [ ] 行揃え
- [ ] 行頭揃え
- [ ] 行末揃え
- [ ] 中央揃え
- [ ] 両端揃え
- [ ] ハイフネーション
- [ ] 縦中横
- [ ] 文字コード

**Comment by terkel** [comment]
残りは #125 に集約。
