### ISSUE TITLE
追加の執筆、修正等

### ISSUE THREAD

**Issue by hrmtrui** [fontplus/web-typography-glossary#119]
図版作成するにあたり記事の読み返しをしまして、
追加執筆と現状記事に関して4点ご相談です。

**①「オブリーク」の記事追加**
https://github.com/fontplus/web-typography-glossary/issues/52
以前オブリークに関して上記のようなやりとりがありましたが、今回図版を作成するにあたって、イタリック体とオブリーク体の違いや、その他の書体の種類と比較し表す必要があるのではないか、ということになりました。

**②「書体」語句の統一**　

（今の記事）
書体（typeface）は、一定の様式でデザインされた字形の集合のことをいいます。たとえばHelveticaやヒラギノ明朝などがそうです。書体の分類として、日本語の明朝体やゴシック体、欧文のセリフ体やサンセリフ体などがあります。

（加筆？）
書体（typeface）は、一定の様式でデザインされた字形の集合のことをいいます。たとえばHelveticaやヒラギノ明朝**体**などがそうです。書体の分類として、日本語の明朝体やゴシック体、欧文のセリフ体やサンセリフ体などがあります。

**③「コンデンスト体」「エクステンデッド体」加筆の可否**

「コンデンスト体」

（今の記事）
コンデンスト体（condensed）は書体のスタイルのひとつで、字幅が狭く縦に細長い形をしているのが特徴です。とくに〜

（加筆？）
コンデンスト体（condensed）は書体のスタイルのひとつで、字幅が狭く縦に細長い形をしているのが特徴です。**一般的に長体と呼ばれます。**とくに〜

「エクステンデッド体」
・もくじが_エクスパンデッド体_になっていているので修正。

（今の記事）
エクステンデッド体（extended）は書体のスタイルのひとつで、字幅が広く横に平べったい形をしているのが特徴です。とくに〜

（加筆？）
エクステンデッド体（extended）は書体のスタイルのひとつで、字幅が広く横に平べったい形をしているのが特徴です。**一般的に平体と呼ばれます。**とくに〜

**Comment by terkel** [comment]
@hrmtrui ありがとうございます！

①オブリークについては僕自身の理解にあやしいところがあるので、いくつか文献にあたるなどしてみます。

②ヒラギノ明朝「体」、たしかにそうですね。直します！

③長体・平体は①同様、ちょっと調査します。目次は直します！

**Comment by terkel** [comment]
@hrmtrui 「コンデンスト体」に「長体」、「エクステンデッド体」に「平体」を追記する件ですが、それぞれの用語は完全に一致するわけではないようなのが難しいところです。「長体」「平体」は「コンデンスト体」「エクステンデッド体」の訳語として使われることもあるようですが、本来そのようにデザインされていない書体を使用者が変形することを「長体・平体をかける」と言うこともあり、「**一般的**に長体と呼ばれます」というのはちょっと無理がありそうです。なので、概要の末尾に「長体と呼ばれることもあります」と軽く付け加えるにとどめてみました。どうでしょう？

**Comment by hrmtrui** [comment]
@terkel 
ご検討ありがとうございます！たしかに、書体自身がコンデンス書体としてデザインされているのと、アプリ上で長体をかけるのはまったく別のことですね・・・！

＞概要の末尾に「長体とも呼ばれます」

とする、よいと思いました！ありがとうございます。
