### ISSUE TITLE
ファイル名

### ISSUE THREAD

**Issue by terkel** [fontplus/web-typography-glossary#12]
欧文由来のものは、たとえば「ウェイト」なら `weight.md` のようにすれば良さそう。ただ「字体」や「異体字」のように、日本語でかつ簡単に英訳が難しいものはどうする？ `jitai.md` `ijitai.md` とか？

**Comment by syyashiro** [comment]
ファイル名について、

外来語

**Comment by terkel** [comment]
ファイル名、現状その方向で膳めています。
ファイルがずらっと並んでしまう問題はたしかに。公開までには考えないと……
