### ISSUE TITLE
禁則処理とhanging-punctuationプロパティ

### ISSUE THREAD

**Issue by matori** [fontplus/web-typography-glossary#124]
禁則処理についてhanging-punctuationプロパティについて触れておくのはどうでしょうか。
https://developer.mozilla.org/ja/docs/Web/CSS/hanging-punctuation

現在実装されているのはSafariだけ（一部機能が使えない）ですが、非常に有用なプロパティだと思います。

**Comment by terkel** [comment]
@matori たしかに。「禁則」に追記する手もありますが、ひょっとすると「ぶら下げ」の項目を新たに作ってもいいのかも。検討します。
