### ISSUE TITLE
リード

### ISSUE THREAD

**Issue by syyashiro** [fontplus/web-typography-glossary#13]

**Comment by syyashiro** [comment]
概要
Webタイポグラフィーに関するキーワードを解説。 日本語でも普及し始めてきたWebフォントだが、英語圏に比べ、そのノウハウは、あまり蓄積されておらず、議論も少ない。 Webフォントサービスを提供するFONTPLUSによるサポートのもと、ウェブと日本語のあり方の議論するための場所をつくる。

と入れています。一旦これで関口さん、土屋さんに確認お願いします。

**Comment by terkel** [comment]
「日本語でも普及し始めてきたWebフォントだが」という部分ですが、Webフォントに限定したくないので、「日本でもWebフォントが普及するなどWebタイポグラフィへの関心が高まっているが……」みたいな感じだとどうでしょう。

あと、現状では「議論するための場所」というより「知見をシェアする場所」という方がイメージ近い気がします。ただここらへんはissueをどう扱うかという話もあり、けっこう難しいところですね。

**Comment by syyashiro** [comment]
下記でブランチにコミットしました。
@terkel @tsuchir レビューをお願いできますと幸いです。

# Webタイポグラフィ必携用語集

Webタイポグラフィに関するキーワードを解説し、日本語ベースのナレッジを蓄積します。  

## 概要

近年、日本語のサイトでもWebフォント導入が進み、Webタイポグラフィへの関心が高まりつつあります。
ただ英語圏と比較すると、そのノウハウは、あまり蓄積されておらず議論も少ないのが現状です。  
本プロジェクトでは、エンジニアやディレクターがWebでタイポグラフィに取り組む際に使えるよう、「実践」の観点からキーワードの解説を行います。  
Webフォントサービスを提供するFONTPLUSによるサポートのもと、日本語のWebタイポグラフィーに関する知見を共有できる場所にできればと考えています。

**Comment by tsuchir** [comment]
「日本語ベースのナレッジを蓄積します。」はもう一声練りたい気がしてます！

また、サポートのくだりは別見出しでクレジットするので、ここでは省略してよいかなとおもいます。

**Comment by tsuchir** [comment]
内容は随時更新していくため、記事内容、タイトル、目次等は今後変更される可能性があります。
みたいにしちゃってもよいかもですね！

**Comment by syyashiro** [comment]
## 概要

近年、日本語のサイトでもWebフォント導入が進み、Webタイポグラフィへの関心が高まりつつあります。  
ただ英語圏と比較すると、そのノウハウはあまり蓄積されておらず議論も少ないのが現状です。  
本プロジェクトでは、エンジニアやディレクターがWebでタイポグラフィに取り組む際に使えるよう、「実践」の観点からキーワードの解説を行います。  
Webタイポグラフィの知見が、日本語で蓄積・共有できる場所になればと考えています。  
（記事内容やタイトル、目次などの内容は、随時更新される可能性があります）

にて、コミットいたしました。
追加でツッコミなどありましたら、
お伺いできればと思います！

@terkel @tsuchir

**Comment by syyashiro** [comment]
# Webタイポグラフィの基礎知識と実践

Webタイポグラフィに関するキーワードを解説、同分野における知見を蓄積・共有します。  

## 概要

近年、日本語のサイトでもWebフォント導入が進み、Webタイポグラフィへの関心が高まりつつあります。  
ただ英語圏と比較すると、そのノウハウはあまり蓄積されておらず議論も少ないのが現状です。  
本プロジェクトでは、エンジニアやディレクターがWebでタイポグラフィに取り組む際に使えるよう、「実践」の観点からキーワードの解説を行います。  
Webタイポグラフィの知見が、日本語で蓄積・共有できる場所になればと考えています。  
（記事内容やタイトル、目次などの内容は、随時更新される可能性があります）

@tsuchir @terkel 

ご確認どうぞよろしくお願いいたします。（タイトルとスレッドまとめました）
何かありましたら、本日明日で対応をさせて頂きます！
