### ISSUE TITLE
イタリック体

### ISSUE THREAD

**Issue by terkel** [fontplus/web-typography-glossary#19]

**Comment by terkel** [comment]
「イタリック」か「イタリック体」か？

**Comment by syyashiro** [comment]
一旦、
『日本国語大辞典』
https://ja.wikipedia.org/wiki/%E6%97%A5%E6%9C%AC%E5%9B%BD%E8%AA%9E%E5%A4%A7%E8%BE%9E%E5%85%B8
を参照するかたちで進めてみましょうか…。
ぼくの方で、統一していきます。
（この場合は「イタリック」）
