### ISSUE TITLE
参考資料

### ISSUE THREAD

**Issue by terkel** [fontplus/web-typography-glossary#23]
書籍やウェブページなど、参考にしたものをまとめておくべき？

**Comment by syyashiro** [comment]
ありがとうございます。
ローンチの段階までで、
一旦まとめていただいて、
これは基礎文献っぽいな…
と思われるものについては、
トップにまとめておいたら
いいような気がします！

**Comment by terkel** [comment]
ひとまずファイル作りました。随時追加していきます。
https://github.com/fontplus/web-typography-glossary/commit/49b89b97b92408fc28a353d63dc3f5de0f53c558
