### ISSUE TITLE
複数の意味

### ISSUE THREAD

**Issue by terkel** [fontplus/web-typography-glossary#24]
複数の解釈や方法がある場合、それらをすべて書くべきか、あるいは取捨選択すべきか？　個人的には、少なくとも最初の段階では、あくまでウェブタイポグラフィの文脈として適切な用法に限定した方がよさそうと思ってます。

**Comment by terkel** [comment]
具体的には「グリフ」がけっこうムズい。
https://tama-san.com/sourcehan-3/#comment-20768

**Comment by syyashiro** [comment]
「グリフ」難しいですね…。
ただ、頂いた原稿読み、
文字と文字のスペースを合わせたデータなんだな…
と結構腹落ちしました！
（合ってますでしょうか…？）

すべての用法を書く必要はなく、
おっしゃるとおり、
WEBタイポグラフィの文脈
とくに実践の文脈で必要なことのみに
限定するのがよいと思います。
