### ISSUE TITLE
フォルダ構成

### ISSUE THREAD

**Issue by terkel** [fontplus/web-typography-glossary#27]
Ref #12 
リポジトリのホームページでMarkdownファイルが大量に並んでしまう問題。

**Comment by terkel** [comment]
`docs`とか。

**Comment by terkel** [comment]
`src`か？

**Comment by syyashiro** [comment]
なるほど。
こちら事情、理解しました。
すぐ下に目次があるので、
フォルダから読者がアクセスする可能性はないため、
同フォルダにまとめるのがよいと思います。

色々ご提案をありがとうございます。

docs

が内容も示しているかつ、
シンプルでいいと思いました。

**Comment by terkel** [comment]
@syyashiro 🙇

**Comment by terkel** [comment]
@syyashiro ただ、このフォルダ名がそのまま公開URLになるので、ちょっと慎重に考えたいですね。

**Comment by syyashiro** [comment]
こちら、少し考えてみました。

/entry/weight.md

はどうでしょう。
見出し、項目という意味もあるので内容的にもしっくりきて、
ブログなどでも使われるのでURLとしても違和感ないかなと思いました。
@terkel

**Comment by syyashiro** [comment]
ありがとうございます！

docs
articles
pages
entry
terms

こう並べてみると、
ご提案いただいたtermsが
一番意味が強くてよいと思います。
（そして、ちょっとかわいい…

termsで移動進めてみます。

**Comment by syyashiro** [comment]
termsにフォルダを
変更しました。
