### ISSUE TITLE
イラストの初回打ち合せについて

### ISSUE THREAD

**Issue by syyashiro** [fontplus/web-typography-glossary#31]
@sekig-ndc @terkel 

先ほど、@itosuzuさんに
このレポジトリへの
参加リクエストをお送りしました。

年始早々7日の週に、
タケルさん、関口さん、矢代、伊藤さん？
4者で全体のトーンをどうするか、
（基本的にはプレーンな図、というテイストがいいと思っています）
今後のフローを再度整理するという打ち合せを
できないかと考えております。

大変恐縮ながら、
7日の週に、海外出張が入ってしまい、
可能であればSkypeなどでお願いできないかと
考えております。

こちら日程調整など、
メールなどでしたほうがよいでしょうか。

ちょっと伊藤さんへのファーストコンタクト、
関口さんにご協力いただければと思いました。

年末のお忙しいところ、
申しわけありません！

**Comment by sekig-ndc** [comment]
@syyashiro 
反応おくれてごめんなさい。ぜひぜひお願いします。続きはSlackで。
