### ISSUE TITLE
TODOの表記

### ISSUE THREAD

**Issue by syyashiro** [fontplus/web-typography-glossary#34]
図版のところについて、

〈TODO〉［図版：Helveticaの書体バリエーション］

という風に、TODOを追記しました。
もし普段の表記方法あれば
お教えいただけますと幸いです！

@terkel

**Comment by terkel** [comment]
@syyashiro ありがとうございます！

ただ、できればカッコを減らしてシンプルにしたいのと、検索しやすさなどを考え、以下の書式にしてみました。

```
*TODO* 図版：Helveticaの書体バリエーション
```

https://github.com/fontplus/web-typography-glossary/commit/b3939b70260f88426cffa71c6732c63b87e45d42

**Comment by terkel** [comment]
@syyashiro たびたび申し訳ないです。ブラウザーで見ると地の文と区別しづらいので、（）で囲んでみました 🙏  https://github.com/fontplus/web-typography-glossary/commit/5df9f61477c20518b85884a59c312975cd900669

```
（*TODO* 図版：Helveticaの書体バリエーション）
```

**Comment by syyashiro** [comment]
ありがとうございます！
（*TODO* 図版：〜〜〜）
の表記で承知をしました。
