### ISSUE TITLE
更新について（仮）

### ISSUE THREAD

**Issue by syyashiro** [fontplus/web-typography-glossary#36]
猿渡さんからご依頼いただいた下記のリクエストについて、
++++
気になる点としましては、承認フローを通すことになった認識でございます。
それに伴いmaster以外はfontplusの確認を通っておらず各個人でやり取りを行っている旨を記述頂きたいのですがいかがでしょうか？
++++

下記のようなテキストを、
Readmeの、
コントリビューティングとライセンスの
間にいれるのはどうでしょう。

+++

## 更新について
毎月ブランチを作成し（ex. feature/2019-01）、コントリビューターとして執筆と編集が更新を行います。また月ごとに、マスターブランチ（master）へのマージを行い、ドキュメントとして公開します。

+++

言葉づかいなど、
一旦こちらを叩きとして
議論できないかと思いました！

@terkel @tsuchir @sekig-ndc

**Comment by sekig-ndc** [comment]
```
毎月トピックブランチを作成し（ex. feature/2019-01）、コントリビューターとして執筆者と編集者が更新を行います。月ごとを目安にマスターブランチ（master）へのマージを行い、正式なドキュメントとして公開していきます。
```

ではどうでしょう。後はぜひたたいてくだされば〜
@syyashiro @terkel @tsuchir

**Comment by syyashiro** [comment]
関口さん、ありがとうございます。
いただいたもの、
僕としては違和感なく、
より正確になっていると思います。

**Comment by tsuchir** [comment]
私もこの内容で異論ありません！

**Comment by tsuchir** [comment]
ex. は例: でもいいかな？てくらい。

**Comment by terkel** [comment]
いいんじゃないでしょうか！

**Comment by syyashiro** [comment]
ありがとうございます。

##更新について
毎月トピックブランチを作成し（例：feature/2019-01）、コントリビューターとして執筆者と編集者が更新を行います。月ごとを目安にマスターブランチ（master）へのマージを行い、正式なドキュメントとして公開していきます。

として、猿渡さんにご確認の依頼をいたします。

**Comment by syyashiro** [comment]
FIXしたのでクローズします
