### ISSUE TITLE
ライセンス

### ISSUE THREAD

**Issue by terkel** [fontplus/web-typography-glossary#4]
Creative Commonsとか？

**Comment by syyashiro** [comment]
非営利で改変可な
CC BY-NC-SA 4.0がいい気がしています。
https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ja

これもチームに確認してみます！

**Comment by syyashiro** [comment]
現在猿渡さんに、ご確認いただいています。

**Comment by syyashiro** [comment]
CC BY-NC-SA 4.0

に確定。

**Comment by syyashiro** [comment]
CC BY-NC-SA 4.0
の方向で現在SBTの広報チェック中。
