### ISSUE TITLE
（仮想）ボディ

### ISSUE THREAD

**Issue by terkel** [fontplus/web-typography-glossary#45]

**Comment by tsuchir** [comment]
> 「文字サイズ」という場合、そのサイズはボディのサイズであり、文字そのもののサイズはフォントによって異なる点に注意が必要です。
ここの「文字そのもののサイズ」というのは、言い換えると「フォントの文字の部分とその周囲のスペース」のうち「その周囲のスペース」を除いた「フォントの文字の部分の大きさ」という意味ですよね。
前半の文をサラッと読むと「ファイルサイズのこと？いや違うか」と一瞬迷ってしまったので、図でその点をフォローすると良いかと思いました。

**Comment by terkel** [comment]
@tsuchir たしかに、ちょっと分かりづらいですね。て言うかよく考えると、ボディの解説として文字サイズの話はいらない気がしてきました。もし文字サイズについて書くならそれはそれで項目を作った方が良さそう。

**Comment by tsuchir** [comment]
@terkel 確かにそのほうがいいと思います！「サイズ」という言葉に対する定義……っていう問題についても（どこまで深掘りするかはさておき）語りやすそうです。
