### ISSUE TITLE
字体

### ISSUE THREAD

**Issue by terkel** [fontplus/web-typography-glossary#5]
- 図形文字の図形表現としての形状についての抽象的概念（JIS X 0208）
- 視覚化する前の文字の骨組みの抽象概念のことを指します（日本語組版入門）
- 図形を一定の文字体系の一字と視覚的に認識する概念、すなわち文字の骨格となる「抽象的な」概念（Wikipedia）
- 文字の点画から成る骨組み（モリサワ）
- ある文字をその文字と視覚的に認識するための概念。 常用漢字表では「字体は文字の骨組みである」としている（type.center）

**Comment by syyashiro** [comment]
字体、翻訳難しいかつ、超複雑ですね。

日本語の「字体」のもつ意味の理解を
促進してあげるという意図でいうと、
いただいているイメージの
Structure of Character
がわかりやすいと思います。

他には、
type（活字）のような、
英単語も参考になるかな？と思いました。

type（小学館 ランダムハウス英和大辞典）
1 (共通の特徴を持ち，1つのグループを成す)類，型，タイプ，様式
5 〔印刷〕
(1)(1個の)活字；タイプライター活字，写真植字の文字.
(2)((集合的に)) 活字；タイプライター活字，写真植字の文字
(3)（印刷された）活字，字体；印刷物
(4)（活字の）字面(face).

**Comment by terkel** [comment]
翻訳の難しいものや、逆に混乱を招きかねないものは、英語表記は載せない方がいいかも。
