### ISSUE TITLE
字間

### ISSUE THREAD

**Issue by terkel** [fontplus/web-typography-glossary#50]

**Comment by tsuchir** [comment]
一般に「文字間」や「文字間隔」と呼ばれているものと同義、と考えていいですよね？
ということを言い添えたほうがいいのかなと思いました。

**Comment by terkel** [comment]
@tsuchir たしかにそうですね。「字間（letter space）は、隣接する文字と文字の間隔のことです。具体的にはボディどうしの間隔を指します。」とかだとどうでしょう？

**Comment by tsuchir** [comment]
@terkel どちらかというと「俗にこうも呼ばれているよ」を示したほうがいいのかな？という意図でした。なので齟齬がなければ下記のようにするのはいかがでしょう？
> 字間（letter space）は、隣接する文字と文字の間隔のことです。具体的にはボディどうしの間隔を指します。「文字間」、「文字間隔」と呼ばれたりもしています。
