### ISSUE TITLE
イタリックとオブリークについて

### ISSUE THREAD

**Issue by sekig-ndc** [fontplus/web-typography-glossary#52]
[イタリック体](https://github.com/fontplus/web-typography-glossary/blob/master/terms/italic.md)への記述の中に、 `oblique` への言及は不要でしょうか？

具体的には、
　
```
font-style: italic;
```
と記述した際と、
　
```
font-style: oblique;
```
と記述した際の、
　

挙動の違いと用法についても記載すると迷いが減るかと思いました。
次回以降どこかで検討いただけますと幸いです。

**Comment by momdo** [comment]
これに関連して、
>そのためブラウザーによる擬似的なイタリックは「にせイタリック（faux italic）」

この文の出典がどこなのか、というのが逆に気になりますが、少なくとも<a href="https://www.w3.org/TR/css-fonts-3/">CSS Fonts Module Level 3</a>では「faux italic」なるフレーズは出てきません。もっとも、synthesize italicといったフレーズは出現しますが、これも仕様内で用語として定まっているというわけでもなさそうですね。

**Comment by sekig-ndc** [comment]
> 少なくともCSS Fonts Module Level 3では「faux italic」なるフレーズは出てきません。

これはわたしの想像ですが、「faux italic」に関してはウェブ標準の枠というより「タイポグラフィ」側の概念と思います。当然、ウェブの標準仕様のなかにまだ包含されていないものもありうるのではないかなと。

そのあたりに関しても、仕様に照らし合わせるのみならず、現実解としての落とし所がみつけていけるといいかなと考えています。

このIssueでのわたしの論点としては、**「斜体」と「イタリック体」は厳密には違うが、いまウェブでそれを扱うにはどうするべきか**、というものでした。

**Comment by momdo** [comment]
> 「斜体」と「イタリック体」は厳密には違うが、いまウェブでそれを扱うにはどうするべきか

まずは「斜体」の項目を先に作成した上で（もちろん作成途中であることは承知しています）、ウェブで斜体なりイタリック体なりを扱うにはどうすべきか、という手順を踏むのがよいのではないでしょうか。（後者に関しては<a href="https://developer.mozilla.org/ja/docs/Web/CSS/font-style">font-style - CSS: カスケーディングスタイルシート | MDN</a>を噛み砕くイメージでしょうか。）

**Comment by terkel** [comment]
> 活字時代には、ローマン体の傾いただけのものを「オブリーク」（oblique）と呼び、明らかに筆記体風のデザインの「イタリック」と区別していましたが、デジタル書体の時代になってまた意味が変わってきました。現在言われている「オブリーク」はローマン体のアウトラインをもとにデータ上で単に傾けただけのものを指します。しかし、単に傾けただけではデザインが崩れるので、最近はイタリック専用に設計されることが増えてきました。それを「イタリック」と呼んでいます。筆記体風でなくても「イタリック」と付く書体が増えてきたのはそのためです。

（小林章『欧文書体　その背景と使い方』美術出版社、2005、p24）

> イタリック体は手書きの特徴が色濃く残っている傾斜書体です。直立体を単に傾斜させたものではなく、小文字のa、f、e、wなどがローマン体と違った独自の形になっています。直立した形をそのまま傾斜させたオブリーク体（oblique）もあります（オブリークという呼び名が一般的ではないので、傾斜書体を単にイタリックと呼ぶこともあります）。

（髙岡昌生『増補改訂版　欧文組版　タイポグラフィの基礎とマナー』美術出版社、2019、p14）

> なお、書体ファミリーにイタリック体がない場合でも、直立体をデザイン・組版ソフトで機械的に傾けて使用するのは避け、オブリーク体を使いましょう。

（同上、p89）

> A slanted version of a Roman typeface made with minimal changes to the normal design. Often confused with italics, oblique faces take a skewed approach using the original character forms of the roman design, while italics typically depart from the roman design.

（Theo Rosendorf, _The Typographic Desk Reference_. Oak Knoll Press, 2016, p187）

このあたりの文献を参考に、イタリック体とオブリーク体については「イタリック体」の項の中で以下のポイントを中心にまとめてみようかと思います。

- ローマン体（立体）を傾けた形でデザインされた書体をオブリーク体と呼ぶことがある
- オブリーク体も傾斜書体の一種としてイタリック体と総称することがある

また、かつてはオブリークと呼ばれていたものがイタリックと総称されることがあるという状況と、`font-style` プロパティの `italic` と `oblique` が相互にフォールバック（？）するというCSSの仕様を考えると、オブリークについてこれ以上は深く立ち入らない方がいい気がしています。

**Comment by sekig-ndc** [comment]
お二方、ありがとうございます。拝読しています。

> このあたりの文献を参考に、イタリック体とオブリーク体については「イタリック体」の項の中で以下のポイントを中心にまとめてみようかと思います。

> 状況
> CSSの仕様


上記指摘と、下記の記事アップデートにより私の疑問はほぼ解消されていますので、Closeしますね。気になられた方いらしたら、改めて議論できればと。
[イタリック体](https://github.com/fontplus/web-typography-glossary/blob/master/terms/italic.md)
