### ISSUE TITLE
両端揃え（ジャスティフィケーション）

### ISSUE THREAD

**Issue by terkel** [fontplus/web-typography-glossary#53]
ほかの揃え（alignment）についてそれぞれ項を立てるか？

- 左揃え（flush left/ragged right）
- 右揃え（flush right/ragged left）
- 両端揃え（justified）
- 中央揃え（centered）

**Comment by tsuchir** [comment]
字間が意図しない大きさになってしまう場合があります。
↓
字間が意図しない間隔になってしまう場合があります。

幅の話なので、「間隔」としたほうがいいように感じました！

**Comment by terkel** [comment]
@tsuchir 🙆‍♂
