### ISSUE TITLE
インデント（字下げ）

### ISSUE THREAD

**Issue by terkel** [fontplus/web-typography-glossary#57]

**Comment by tsuchir** [comment]
1点相談です。欧文で、エディタ上ではtabキーを用いるような1字下げではないサイズのインデントは、ここでは言及しないほうがいいでしょうか？

https://bunkyo-kumihan.com/kumihan_blog/?p=3733

**Comment by terkel** [comment]
@tsuchir たしかに、欧文に限らず和文でも段落先頭2字下げ3字下げがあるし、中国語では2字下げが基本らしいので、インデント幅についてちょっと解説してもいいかもしれないですね。考えてみます。
tabキーについてはタイポグラフィの範囲を超える気がするので、ふれなくていいかなーと思ってます。

**Comment by tsuchir** [comment]
@terkel 
> tabキーについてはタイポグラフィの範囲を超える気がするので、ふれなくていいかなーと思ってます。

了解です！
インデント幅については、一旦は現状内容でリリースしつつ、次回ふくらませるでもOKです。
