### ISSUE TITLE
行揃え

### ISSUE THREAD

**Issue by terkel** [fontplus/web-typography-glossary#66]
`text-align`

**Comment by tsuchir** [comment]
なじみのある他の呼び名はあるんだろうか？と思いWordとGoogle Docsを開いたら「配置」と呼ばれていましたね。
また、ブログなどでは「文字揃え」と呼ばれていたりしますが、これは用法が間違いの可能性ありますよね（「文字揃え」はinline＝個別の文字単位の揃え、「行揃え」はblock＝段落全体に対して、という違いがありそう）​。

といったところ踏まえて、下記のように加えるとなじみが持てるかな？と思いました。

行揃え（text alignment）とは、行の中の文字列を揃える方法をいいます。
↓
行揃え（text alignment）とは、行の中の文字列を揃える方法をいいます。Wordなどの文書​​作成ソフトでは「配置」とも呼ばれています。

文字揃えについては、説明の複雑度合いによって検討したいです。

またここで、「行頭揃え」「行末揃え」「中央揃え」「両端揃え」の違いを見た目で一覧できる図があるといいかもですね！

**Comment by terkel** [comment]
@tsuchir 「配置」を加える案、良いと思います！
「文字揃え」は、ご指摘のとおり、ベースライン揃えや上揃えなど上下方向（縦書きのときは左右方向）の揃えを指すのが一般的っぽいです。これは別項目を立てる予定です（#67）。

**Comment by terkel** [comment]
@itosuzu 一覧の図もぜひお願いしたいです！

**Comment by tsuchir** [comment]
@terkel ありがとうございます。文字揃えを別立ての件了解です！図版も原稿に記載しておきます。
