### ISSUE TITLE
行送り

### ISSUE THREAD

**Issue by terkel** [fontplus/web-typography-glossary#69]

**Comment by tsuchir** [comment]
ある行の基準点（ベースラインなど）からその次の行の基準点までの距離
↓
ある行の基準線（ラテンアルファベットはベースライン、​​日本語は仮想ボディの中央など）からその次の行の基準線までの距離

点→線、そして「ベースラインなど」のなど部分を若干ふくらませるとわかりやすいかなと感じました！

またここの図版は、その「線」の位置や線同士の関係を表すようなものであればOKですよね。

**Comment by terkel** [comment]
@tsuchir 基準点→基準線、たしかにそうですね、それでいきましょう！

で、その基準線がどこかについてどう説明するかはけっこう難しいんですよね。そもそもCSSでは行送りというより行ボックスを積み上げていくイメージなので、あまり細かく書いても混乱しそうだし。あと日本語は基準線がいいろいろ考えられるので、そこらへん誤解のないように書こうとするとややこしくなるし……（参考 http://works014.hatenablog.com/entry/20160930）

いずれにせよカッコ内で説明しきるのは難しそうなので、ちょっと考えてみます。

**Comment by terkel** [comment]
@tsuchir とは言えウェブでは横組みでベースライン揃えがデフォルトだし、組版でも横組み和欧混植ではベースラインを基準に考えたりもするようだし、いたずらにセンター基準を持ち出さない方が良さそうな気がしてきました。そのかわり、図版で欧文ベースライン基準と和文縦組みセンター基準の2つを見せられるといいのでは。どうでしょう？

**Comment by tsuchir** [comment]
@terkel 
> 図版で欧文ベースライン基準と和文縦組みセンター基準の2つを見せられるといいのでは。
ですね、スタンダードな例を見せる形で、良いと思います！

**Comment by terkel** [comment]
@tsuchir ありがとうございます。ではお手数ですが、基準点→基準線の修正をお願いしちゃっていいですか？
