### ISSUE TITLE
図版作成

### ISSUE THREAD

**Issue by tsuchir** [fontplus/web-typography-glossary#70]
以下10点、各ページ内に図版内容の指定がありますのでご確認の上作成お願いします。

- [x] 字体
https://github.com/fontplus/web-typography-glossary/blob/master/terms/jitai.md

- [x] 字形
https://github.com/fontplus/web-typography-glossary/blob/master/terms/jikei.md

- [x] 書体
https://github.com/fontplus/web-typography-glossary/blob/master/terms/typeface.md

- [x] グリフ
https://github.com/fontplus/web-typography-glossary/blob/master/terms/glyph.md

- [x] ファミリー
https://github.com/fontplus/web-typography-glossary/blob/master/terms/family.md

- [x] ウェイト
https://github.com/fontplus/web-typography-glossary/blob/master/terms/weight.md

- [x] イタリック体
https://github.com/fontplus/web-typography-glossary/blob/master/terms/italic.md

- [x] 等幅フォント
https://github.com/fontplus/web-typography-glossary/blob/master/terms/monospaced-font.md

- [x] サイドベアリング
https://github.com/fontplus/web-typography-glossary/blob/master/terms/side-bearing.md

- [x] プロポーショナルメトリクス
https://github.com/fontplus/web-typography-glossary/blob/master/terms/proportional-metrics.md

以下は、図版内容を検討したいです。

- [x] ボディ
https://github.com/fontplus/web-typography-glossary/blob/master/terms/body.md

- [x] 字面
https://github.com/fontplus/web-typography-glossary/blob/master/terms/face.md

- [x] 全角
https://github.com/fontplus/web-typography-glossary/blob/master/terms/fullwidth.md

- [ ] 字間
https://github.com/fontplus/web-typography-glossary/blob/master/terms/letter-space.md

- [ ] ベタ組み
https://github.com/fontplus/web-typography-glossary/blob/master/terms/betagumi.md

- [ ] カーニング
https://github.com/fontplus/web-typography-glossary/blob/master/terms/kerning.md

- [ ] トラッキング
https://github.com/fontplus/web-typography-glossary/blob/master/terms/tracking.md

**Comment by terkel** [comment]
残りは #125 に集約。
